const UA='Mozilla/5.0 (compatible; ClariNavi/Current; +https://vercel.app)';
function num(v){if(v==null)return null;const n=Number(String(v).replace(/,/g,'').replace(/%/g,'').replace(/－|--/g,'').trim());return Number.isFinite(n)?n:null}
function txt(v){return String(v??'').replace(/\s+/g,' ').trim()}
async function json(url,timeout=6000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':UA,'Accept':'application/json,*/*'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function dates(days=50){const a=[],d=new Date();for(let i=1;i<=days;i++){const x=new Date(d);x.setDate(d.getDate()-i);if(x.getDay()===0||x.getDay()===6)continue;a.push(`${x.getFullYear()}${String(x.getMonth()+1).padStart(2,'0')}${String(x.getDate()).padStart(2,'0')}`)}return a}
async function mapLimit(items,limit,fn){let i=0,out=[];async function w(){while(i<items.length){const j=i++;try{out[j]=await fn(items[j])}catch{out[j]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},w));return out}
function rowFromFields(fields,row,code){const f=fields.map(x=>txt(x));if(String(row?.[0]||'').trim()!==code)return null;const get=(term)=>{const i=f.findIndex(x=>x.includes(term));return i>=0?num(row[i]):null};const foreign=(get('外陸資買賣超股數(不含外資自營商)')??get('外陸資買賣超股數')??0)+(get('外資自營商買賣超股數')??0);return {foreign,trust:get('投信買賣超股數'),dealer:get('自營商買賣超股數'),total:get('三大法人買賣超股數')}
}
async function instOne(code,d){const j=await json(`https://www.twse.com.tw/rwd/zh/fund/T86?date=${d}&selectType=ALLBUT0999&response=json`,5500);if(j?.stat!=='OK'||!Array.isArray(j.data))return null;const r=j.data.map(x=>rowFromFields(j.fields||[],x,code)).find(Boolean);return r?{date:`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}`,...r}:null}
function marginFromTable(fields,row,code){const ff=(fields||[]).map(x=>txt(x));const idxCode=ff.findIndex(x=>x==='代號'||x.includes('股票代號')||x.includes('證券代號'));const codeCell=idxCode>=0?txt(row[idxCode]):txt(row?.[0]);if(codeCell!==code)return null;const find=(terms)=>{for(let i=0;i<ff.length;i++)if(terms.some(t=>ff[i].replace(/\s/g,'').includes(t)))return num(row[i]);return null};return {marginBuy:find(['融資買進','買進']),marginSell:find(['融資賣出','賣出']),marginBalance:find(['融資今日餘額','今日餘額']),shortBuy:find(['融券買進']),shortSell:find(['融券賣出']),shortBalance:find(['融券今日餘額'])}}
function scanMarginJson(j,code){const candidates=[];if(Array.isArray(j?.data))candidates.push({fields:j.fields||[],data:j.data});for(const t of j?.tables||[])if(Array.isArray(t?.data))candidates.push({fields:t.fields||[],data:t.data});for(const c of candidates){for(const r of c.data){if(!Array.isArray(r))continue;const x=marginFromTable(c.fields,r,code);if(x&&Number.isFinite(x.marginBalance))return x}}return null}
async function marginOne(code,d){const j=await json(`https://www.twse.com.tw/rwd/zh/marginTrading/MI_MARGN?date=${d}&response=json&selectType=ALL`,5500);const x=scanMarginJson(j,code);return x?{date:`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}`,...x}:null}
async function twse(code){const ds=dates(55);const [ir,mr]=await Promise.all([mapLimit(ds.slice(0,18),6,d=>instOne(code,d)),mapLimit(ds.slice(0,16),5,d=>marginOne(code,d))]);const institutional=ir.filter(Boolean).sort((a,b)=>a.date.localeCompare(b.date)).slice(-15);const marginHistory=mr.filter(Boolean).sort((a,b)=>a.date.localeCompare(b.date)).slice(-15);return {institutional,marginHistory,coverage:{institutionalDays:institutional.length,marginDays:marginHistory.length},source:'TWSE T86 / MI_MARGN 歷史公開查詢',note:'背離雷達使用公開盤後法人與融資餘額；不是盤中即時法人下單。'} }
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=900, stale-while-revalidate=3600');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Content-Type','application/json; charset=utf-8');const code=txt(req.query?.code).toUpperCase(),market=txt(req.query?.market||'TWSE').toUpperCase();if(!/^\d{4,6}[A-Z]?$/.test(code))return res.status(400).json({error:'代號格式錯誤'});try{if(market!=='TWSE')return res.status(200).json({code,market,institutional:[],marginHistory:[],coverage:{institutionalDays:0,marginDays:0},source:'TPEx',note:'目前歷史法人×融資背離雷達先完整支援上市股票；上櫃保留現行單日籌碼，不產生假歷史序列。'});return res.status(200).json({code,market:'TWSE',...(await twse(code))})}catch(e){return res.status(200).json({code,market,institutional:[],marginHistory:[],error:e.message,source:'TWSE'})}}
