const TWSE='https://openapi.twse.com.tw/v1';
const MIS='https://mis.twse.com.tw/stock/api/getStockInfo.jsp';
const UA='Mozilla/5.0 (compatible; ClariNavi/Current; official ETF directory)';
const cache=new Map();
const txt=v=>String(v??'').replace(/\u3000/g,' ').replace(/\s+/g,' ').trim();
const num=v=>{const n=Number(String(v??'').replace(/,/g,'').replace(/%/g,'').trim());return Number.isFinite(n)?n:null};
const pick=(o,ks)=>{for(const k of ks)if(o&&o[k]!=null&&txt(o[k])!=='')return o[k];return null};
async function fetchJson(url,ms=7000,headers={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':UA,'Accept':'application/json,text/plain,*/*',...headers}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function cached(k,ttl,fn){const h=cache.get(k);if(h&&Date.now()-h.t<ttl)return h.v;const v=await fn();cache.set(k,{t:Date.now(),v});return v}
function classifyETF(name,type,benchmark){const s=`${name} ${type} ${benchmark}`.toLowerCase();if(/主動/.test(s))return'active';if(/反向|反1|inverse/.test(s))return'inverse';if(/槓桿|正2|正二|2x|兩倍/.test(s))return'leveraged';if(/債|bond|fixed income|公債|公司債|投資級|非投資級|高收益/.test(s))return'bond';if(/股票|stock|equity|指數/.test(s))return'equity';return'other'}
function metaRow(r){const code=txt(pick(r,['基金代號','證券代號','Code','基金證券代號']));if(!/^00\w{2,6}$/i.test(code)&&!/^\d{4,6}[A-Z]?$/.test(code))return null;const name=txt(pick(r,['基金簡稱','基金中文名稱','基金名稱','證券簡稱','Name']))||code,type=txt(pick(r,['基金類型','Type'])),benchmark=txt(pick(r,['標的指數/追蹤指數名稱','標的指數','追蹤指數','Benchmark'])),foreignRaw=txt(pick(r,['是否包含國外成分股','ForeignComponents','含國外成分股']));return{code,name,type,benchmark,category:classifyETF(name,type,benchmark),foreign:/^(是|y|yes|true|1)$/i.test(foreignRaw),listingDate:txt(pick(r,['上市日期','掛牌日期','ListingDate'])),units:num(pick(r,['發行單位數/轉換數','發行單位數','Units']))}}
async function directory(){return cached('dir',6*3600_000,async()=>{const [meta,day,regular]=await Promise.allSettled([fetchJson(`${TWSE}/opendata/t187ap47_L`),fetchJson(`${TWSE}/exchangeReport/STOCK_DAY_ALL`),fetchJson(`${TWSE}/ETFReport/ETFRank`)]);const dm=new Map();for(const r of day.status==='fulfilled'&&Array.isArray(day.value)?day.value:[]){const c=txt(r.Code);if(c)dm.set(c,r)}const rm=new Map();for(const r of regular.status==='fulfilled'&&Array.isArray(regular.value)?regular.value:[]){const c=txt(pick(r,['證券代號','ETF代號','股票代號','Code','SecurityCode']));if(!c)continue;const accounts=num(pick(r,['交易戶數','定期定額交易戶數','TradingAccounts','Accounts','戶數'])),rank=num(pick(r,['排名','Rank'])),month=txt(pick(r,['月份','年月','Month']));const old=rm.get(c);if(!old||(month&&month>old.month))rm.set(c,{accounts,rank,month})}const rows=[];for(const r of meta.status==='fulfilled'&&Array.isArray(meta.value)?meta.value:[]){const m=metaRow(r);if(!m)continue;const d=dm.get(m.code)||{},price=num(pick(d,['ClosingPrice','Close'])),chg=num(pick(d,['Change'])),prev=chg!=null&&price!=null?price-chg:null,rawVol=num(pick(d,['TradeVolume','TradingVolume'])),vol=rawVol==null?null:rawVol/1000,turn=num(pick(d,['TradeValue'])),reg=rm.get(m.code)||{};rows.push({...m,price,change:chg,changePct:chg!=null&&prev?chg/prev*100:null,volume:vol,turnover:turn,regularAccounts:reg.accounts,regularRank:reg.rank,regularMonth:reg.month})}return rows})}
function sortRows(rows,sort){const a=[...rows];if(sort==='change')return a.sort((x,y)=>(y.changePct??-999)-(x.changePct??-999));if(sort==='loss')return a.sort((x,y)=>(x.changePct??999)-(y.changePct??999));if(sort==='price')return a.sort((x,y)=>(y.price??-1)-(x.price??-1));if(sort==='regular')return a.sort((x,y)=>(x.regularRank??9999)-(y.regularRank??9999)||(y.regularAccounts??-1)-(x.regularAccounts??-1));if(sort==='units')return a.sort((x,y)=>(y.units??-1)-(x.units??-1));return a.sort((x,y)=>(y.volume??-1)-(x.volume??-1))}
async function liveQuotes(rows){const out=new Map(),groups=[];for(let i=0;i<rows.length;i+=45)groups.push(rows.slice(i,i+45));await Promise.allSettled(groups.map(async g=>{const ch=g.map(x=>`tse_${x.code}.tw`);const j=await fetchJson(`${MIS}?ex_ch=${encodeURIComponent(ch.join('|'))}&json=1&delay=0&_=${Math.floor(Date.now()/5000)}`,4200,{Referer:'https://mis.twse.com.tw/stock/fibest.jsp'});for(const q of Array.isArray(j?.msgArray)?j.msgArray:[]){const code=txt(q.c),price=num(q.z)??num(q.y),prev=num(q.y),chg=price!=null&&prev!=null?price-prev:null;out.set(code,{price,change:chg,changePct:chg!=null&&prev?chg/prev*100:null,volume:num(q.v),time:txt(q.t),live:num(q.z)!=null})}}));return out}
module.exports=async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','s-maxage=10, stale-while-revalidate=20');const sort=['volume','change','loss','price','regular','units'].includes(String(req.query?.sort))?String(req.query.sort):'volume',limit=Math.min(100,Math.max(10,Number(req.query?.limit)||50)),q=txt(req.query?.q).toUpperCase(),kind=['all','equity','bond','leveraged','inverse','foreign','active'].includes(String(req.query?.kind))?String(req.query.kind):'all';try{let rows=await directory();if(q)rows=rows.filter(x=>x.code.includes(q)||x.name.toUpperCase().includes(q)||x.type.toUpperCase().includes(q)||x.benchmark.toUpperCase().includes(q));if(kind!=='all')rows=rows.filter(x=>kind==='foreign'?x.foreign:x.category===kind);const candidates=sortRows(rows,sort).slice(0,Math.max(limit,120)),live=sort==='regular'||sort==='units'?new Map():await liveQuotes(candidates);const merged=candidates.map(x=>live.has(x.code)?{...x,...live.get(x.code)}:x),items=sortRows(merged,sort).slice(0,limit).map((x,i)=>({...x,rank:i+1,volumeUnit:'張'}));return res.status(200).json({ok:true,sort,kind,items,total:rows.length,updatedAt:new Date().toISOString(),refreshSeconds:10,source:'TWSE 基金基本資料彙總表 + TWSE STOCK_DAY_ALL + TWSE MIS + TWSE ETFRank',license:'TWSE 官方公開介面／政府資料開放授權條款第1版適用資料',note:'ETF 清單與定期定額排行採 TWSE 官方公開資料；盤中價格與成交量在可取得時以 TWSE MIS 最佳努力更新。分類依官方基金名稱、類型與追蹤指數欄位規則化，不推估不存在的資產規模或報酬資料。'});}catch(e){return res.status(200).json({ok:false,kind,items:[],error:e?.name==='AbortError'?'資料來源逾時':e.message,source:'TWSE 官方公開資料'});}}