const UA='Mozilla/5.0 (compatible; ClariNavi/Current; public research UI)';
function clean(v=''){return String(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g,' ').trim()}
function num(v){const x=Number(String(v??'').replace(/,/g,'').replace(/%/g,'').trim());return Number.isFinite(x)?x:null}
function roc(v){const m=String(v||'').match(/(\d{2,3})\/(\d{1,2})\/(\d{1,2})/);if(!m)return null;return `${Number(m[1])+1911}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`}
function cells(row){return [...row.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(m=>clean(m[1]))}
function parse(html){const out=[];for(const m of html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const c=cells(m[1]);if(c.length<12||!/^[0-9]{4,6}[A-Z]?$/.test(c[3]||''))continue;const market=c[4]||'';if(/公債|公司債|債券/.test(market))continue;const actual=num(c[10]),tentative=num(c[9]);out.push({drawDate:roc(c[1]),name:c[2],code:c[3],market,applyStart:roc(c[5]),applyEnd:roc(c[6]),underwriteShares:num(c[7]),actualShares:num(c[8]),price:actual??tentative,priceText:actual!=null?String(actual):tentative!=null?`${tentative}（暫定）`:'未訂出',priceFinal:actual!=null,allocationDate:roc(c[11]),broker:c[12]||'',applyShares:num(c[13]),totalAmount:num(c[14]),qualified:num(c[15]),winRate:num(c[16]),cancelled:!!clean(c[17])});}
 return out;
}
function status(x,today){const a=x.applyStart?new Date(x.applyStart+'T00:00:00'):null,b=x.applyEnd?new Date(x.applyEnd+'T23:59:59'):null,d=x.drawDate?new Date(x.drawDate+'T23:59:59'):null;if(x.cancelled)return'已取消';if(a&&today<a)return'即將開始';if(a&&b&&today>=a&&today<=b)return'申購中';if(d&&today<=d)return'等待抽籤';return'已抽籤'}
module.exports=async function handler(req,res){res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','s-maxage=900, stale-while-revalidate=3600');const y=Number(req.query?.year)||new Date().getFullYear();const url=`https://www.twse.com.tw/announcement/publicForm?response=html&yy=${y}`;try{const c=new AbortController(),tm=setTimeout(()=>c.abort(),7000);let r;try{r=await fetch(url,{signal:c.signal,headers:{'User-Agent':UA,'Accept':'text/html,*/*','Referer':'https://www.twse.com.tw/'}})}finally{clearTimeout(tm)}if(!r.ok)throw new Error(`TWSE HTTP ${r.status}`);const rows=parse(await r.text()),now=new Date();const items=rows.map(x=>({...x,status:status(x,now),source:'TWSE 公開申購公告'})).sort((a,b)=>String(a.applyStart||a.drawDate||'').localeCompare(String(b.applyStart||b.drawDate||'')));return res.status(200).json({items,updatedAt:new Date().toISOString(),sourceUrl:url,note:'公開申購日期與實際承銷價可能變動，請以主辦券商與 TWSE 最新承銷公告為準。'});}catch(e){return res.status(200).json({items:[],updatedAt:new Date().toISOString(),sourceUrl:url,error:e?.name==='AbortError'?'TWSE 公開申購來源逾時':e.message,note:'來源暫時不可用時不顯示推估資料。'});}}
