const UA='Mozilla/5.0 (compatible; ClariNavi/Current; public research feed)';
const PRESETS=[
 {id:'trump-truth',name:'Donald Trump',role:'U.S. President',platform:'Truth Social',type:'truth',handle:'realDonaldTrump',url:'https://truthsocial.com/@realDonaldTrump',auto:true,featured:true},
 {id:'musk-x',name:'Elon Musk',role:'Tesla / xAI',platform:'X',type:'x',handle:'elonmusk',url:'https://x.com/elonmusk',featured:true},
 {id:'jensen-official',name:'Jensen Huang',role:'NVIDIA CEO',platform:'NVIDIA Blog',type:'nvidia',url:'https://blogs.nvidia.com/blog/author/jen-hsun-huang/',auto:true,featured:true},
 {id:'banini-fb',name:'吃土鋁繩-巴逆逆',role:'公開 KOL',platform:'Facebook',type:'facebook',handle:'diewithoutbang',url:'https://www.facebook.com/diewithoutbang',featured:true},
 {id:'cook-x',name:'Tim Cook',role:'Apple CEO',platform:'X',type:'x',handle:'tim_cook',url:'https://x.com/tim_cook'},
 {id:'nadella-x',name:'Satya Nadella',role:'Microsoft CEO',platform:'X',type:'x',handle:'satyanadella',url:'https://x.com/satyanadella'},
 {id:'pichai-x',name:'Sundar Pichai',role:'Alphabet CEO',platform:'X',type:'x',handle:'sundarpichai',url:'https://x.com/sundarpichai'},
 {id:'jassy-x',name:'Andy Jassy',role:'Amazon CEO',platform:'X',type:'x',handle:'ajassy',url:'https://x.com/ajassy'},
 {id:'zuck-threads',name:'Mark Zuckerberg',role:'Meta CEO',platform:'Threads',type:'link',url:'https://www.threads.net/@zuck'}
];
function clean(s){return String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim()}
function safeHandle(v,kind){v=String(v||'').trim().replace(/^@/,'');if(kind==='x')return /^[A-Za-z0-9_]{1,15}$/.test(v)?v:'';if(kind==='truth')return /^[A-Za-z0-9_.-]{1,40}$/.test(v)?v:'';if(kind==='facebook')return /^[A-Za-z0-9_.-]{1,80}$/.test(v)?v:'';return''}
function customSources(req){const out=[];for(const [q,type,platform,base] of [['xHandles','x','X','https://x.com/'],['truthHandles','truth','Truth Social','https://truthsocial.com/@'],['fbHandles','facebook','Facebook','https://www.facebook.com/']]){const vals=String(req.query?.[q]||'').split(',').slice(0,8);for(const raw of vals){const handle=safeHandle(raw,type);if(!handle)continue;out.push({id:`custom-${type}-${handle.toLowerCase()}`,name:`@${handle}`,role:'自訂追蹤',platform,type,handle,url:base+handle,custom:true})}}return out}
async function fetchText(url,opts={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(url,{...opts,signal:c.signal,headers:{'User-Agent':UA,'Accept':'application/json,text/html,*/*',...(opts.headers||{})}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
async function truth(src){const lookup=JSON.parse(await fetchText(`https://truthsocial.com/api/v1/accounts/lookup?acct=${encodeURIComponent(src.handle)}`));const rows=JSON.parse(await fetchText(`https://truthsocial.com/api/v1/accounts/${lookup.id}/statuses?exclude_replies=true&limit=8`));return rows.map(x=>({id:`${src.id}-${x.id}`,sourceId:src.id,source:src.name,role:src.role,platform:src.platform,text:clean(x.content),date:x.created_at,url:x.url||src.url,kind:'post'}))}
async function xfeed(src){const token=process.env.X_BEARER_TOKEN;if(!token)return [];const q=`from:${src.handle} -is:retweet`;const url=`https://api.x.com/2/tweets/search/recent?query=${encodeURIComponent(q)}&max_results=10&tweet.fields=created_at`;const j=JSON.parse(await fetchText(url,{headers:{Authorization:`Bearer ${token}`}}));return (j.data||[]).map(x=>({id:`${src.id}-${x.id}`,sourceId:src.id,source:src.name,role:src.role,platform:'X',text:clean(x.text),date:x.created_at,url:`https://x.com/${src.handle}/status/${x.id}`,kind:'post'}))}
async function nvidia(src){const h=await fetchText(src.url);const items=[];const re=/<a[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(h))&&items.length<18){const title=clean(m[2]),u=m[1];if(!title||title.length<8||title.length>220)continue;if(!/^https?:\/\//.test(u)&&!u.startsWith('/'))continue;if(/^(read|learn|more|next|previous|nvidia|blog)$/i.test(title))continue;const url=u.startsWith('http')?u:`https://blogs.nvidia.com${u}`;if(items.some(x=>x.url===url))continue;items.push({id:`${src.id}-${items.length}`,sourceId:src.id,source:src.name,role:src.role,platform:src.platform,text:title,date:null,url,kind:'official'})}return items.slice(0,8)}
async function facebook(src){const token=process.env.META_PAGE_ACCESS_TOKEN;if(!token)return [];const ver=process.env.META_GRAPH_VERSION||'v22.0';const meta=JSON.parse(await fetchText(`https://graph.facebook.com/${ver}/${encodeURIComponent(src.handle)}?fields=id,name&access_token=${encodeURIComponent(token)}`));if(!meta.id)return[];const j=JSON.parse(await fetchText(`https://graph.facebook.com/${ver}/${meta.id}/posts?fields=message,created_time,permalink_url&limit=8&access_token=${encodeURIComponent(token)}`));return (j.data||[]).map(x=>({id:`${src.id}-${x.id}`,sourceId:src.id,source:src.name,role:src.role,platform:'Facebook',text:clean(x.message),date:x.created_time,url:x.permalink_url||src.url,kind:'post'}))}
function stateFor(src){if(src.type==='truth'||src.type==='nvidia')return'live';if(src.type==='x')return process.env.X_BEARER_TOKEN?'live':'auth';if(src.type==='facebook')return process.env.META_PAGE_ACCESS_TOKEN?'live':'auth';return'link'}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=240');res.setHeader('Content-Type','application/json; charset=utf-8');const ids=String(req.query?.ids||'').split(',').map(x=>x.trim()).filter(Boolean),custom=customSources(req);const picked=[...(ids.length?PRESETS.filter(x=>ids.includes(x.id)):PRESETS.filter(x=>x.featured)),...custom];const out=[],states=[];for(const src of picked){try{let rows=[];if(src.type==='truth')rows=await truth(src);else if(src.type==='x')rows=await xfeed(src);else if(src.type==='nvidia')rows=await nvidia(src);else if(src.type==='facebook')rows=await facebook(src);out.push(...rows);const state=stateFor(src);states.push({...src,state,note:state==='live'?'可自動更新':state==='auth'?'需站方設定官方 API 授權；未授權時仍提供原始帳號入口':'提供官方帳號入口'});}catch(e){states.push({...src,state:'error',note:`來源暫時無法更新：${e.message}`})}}
out.sort((a,b)=>(Date.parse(b.date||0)||0)-(Date.parse(a.date||0)||0));return res.status(200).json({sources:states,catalog:PRESETS.map(x=>({...x,state:stateFor(x)})),items:out.slice(0,60),updatedAt:new Date().toISOString(),capabilities:{truth:'public-interface',x:process.env.X_BEARER_TOKEN?'api-enabled':'api-key-required',facebook:process.env.META_PAGE_ACCESS_TOKEN?'api-enabled':'page-token-required',nvidia:'official-web'},note:'只讀取公開介面、官方網站或經平台 API 授權取得的內容；不繞過登入、付費牆或平台限制。'});}
