const UA='Mozilla/5.0 (compatible; ClariNavi/Current; public market alerts)';
const SOURCES={twNotice:'https://openapi.twse.com.tw/v1/announcement/notice',twPunish:'https://openapi.twse.com.tw/v1/announcement/punish',otcNotice:'https://www.tpex.org.tw/openapi/v1/tpex_trading_warning_information',otcPunish:'https://www.tpex.org.tw/openapi/v1/tpex_disposal_information'};
function s(v){return String(v??'').trim()}
function pick(o,keys){for(const k of keys)if(o?.[k]!=null&&s(o[k]))return s(o[k]);return''}
function roc8(v){const x=s(v).replace(/\D/g,'');if(x.length===7){const y=Number(x.slice(0,3))+1911;return `${y}-${x.slice(3,5)}-${x.slice(5,7)}`}const m=s(v).match(/(\d{2,3})[\/.-](\d{1,2})[\/.-](\d{1,2})/);if(m)return`${Number(m[1])+1911}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;if(/^20\d{2}-\d{2}-\d{2}$/.test(s(v)))return s(v);return s(v)}
async function json(url){const c=new AbortController(),tm=setTimeout(()=>c.abort(),5500);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':UA,'Accept':'application/json,text/plain,*/*','Referer':url.includes('tpex')?'https://www.tpex.org.tw/':'https://www.twse.com.tw/'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(tm)}}
function fallbackDetail(o){return Object.entries(o||{}).filter(([k,v])=>v!=null&&s(v)&&!/^Number$/i.test(k)).slice(0,18).map(([k,v])=>`${k}：${s(v)}`).join('\n')}
function normalize(o,market,type){const code=pick(o,['Code','code','SecuritiesCode','SecurityCode','SecuritiesCompanyCode','證券代號','股票代號','股票代碼','代號']);const name=pick(o,['Name','name','CompanyName','SecuritiesName','證券名稱','股票名稱','公司名稱','名稱']);const date=roc8(pick(o,['Date','date','AnnouncementDate','公布日期','公告日期','日期']));const reason=pick(o,['ReasonsOfDisposition','Reason','reason','TradingInformation','AttentionInformation','WarningInformation','注意交易資訊','處置原因','注意原因','原因']);const period=pick(o,['DispositionPeriod','Period','處置期間','期間']);const measure=pick(o,['DispositionMeasures','Measures','處置措施','措施']);const detail=pick(o,['Detail','detail','Details','詳細內容','說明'])||fallbackDetail(o);return{market,type,date,code,name,reason:reason||(/disposition/.test(type)?measure:'詳見官方公告'),period,measure,detail,sourceUrl:market==='TWSE'?(type==='disposition'?'https://www.twse.com.tw/zh/announcement/punish.html':'https://www.twse.com.tw/zh/announcement/notice.html'):'https://www.tpex.org.tw/zh-tw/announce/market/attention.html'} }
module.exports=async function handler(req,res){res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','s-maxage=90, stale-while-revalidate=300');const code=s(req.query?.code).toUpperCase(),items=[],errors=[];const jobs=[['TWSE','notice',SOURCES.twNotice],['TWSE','disposition',SOURCES.twPunish],['TPEx','notice',SOURCES.otcNotice],['TPEx','disposition',SOURCES.otcPunish]];await Promise.all(jobs.map(async([market,type,url])=>{try{const j=await json(url),arr=Array.isArray(j)?j:Array.isArray(j?.data)?j.data:[];for(const row of arr){const x=normalize(row,market,type);if(x.code&&( !code||x.code===code))items.push(x)}}catch(e){errors.push(`${market} ${type}: ${e.message}`)}}));const key=x=>`${x.market}|${x.type}|${x.date}|${x.code}|${x.period}`;const uniq=[...new Map(items.map(x=>[key(x),x])).values()].sort((a,b)=>String(b.date).localeCompare(String(a.date)));return res.status(200).json({items:uniq,updatedAt:new Date().toISOString(),errors,note:'「注意股票」是交易風險提醒，不等同「處置股票」；處置措施與期間以交易所最新公告為準。'});}
