const lastGoodQuote=new Map();
const MIS_URL='https://mis.twse.com.tw/stock/api/getStockInfo.jsp';
function n(v){const x=Number(String(v??'').replace(/,/g,'').trim());return Number.isFinite(x)?x:null;}
function list(v){return String(v||'').split('_').map(n).filter(Number.isFinite);}
async function fetchJson(url,ms=4500,headers={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0 (compatible; ClariNavi/Current)','Accept':'application/json,text/plain,*/*',...headers}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function mis(code){const channels=`tse_${code}.tw|otc_${code}.tw`;const j=await fetchJson(`${MIS_URL}?ex_ch=${encodeURIComponent(channels)}&json=1&delay=0&_=${Date.now()}`,3500,{Referer:'https://mis.twse.com.tw/stock/fibest.jsp'});const arr=Array.isArray(j?.msgArray)?j.msgArray:[];const matches=arr.filter(x=>String(x.c||'').trim()===code&&['tse','otc'].includes(String(x.ex||'').toLowerCase()));if(!matches.length)return null;const q=matches.find(x=>n(x.z)!=null)||matches.find(x=>x.n&&x.n!=='-')||matches[0],price=n(q.z)??n(q.y),prev=n(q.y),change=price!=null&&prev!=null?price-prev:null;return{available:true,code,name:q.n||code,market:String(q.ex).toLowerCase()==='tse'?'TWSE':'TPEx',date:String(q.d||''),time:String(q.t||''),timestamp:n(q.tlong),price,prevClose:prev,change,changePct:change!=null&&prev?change/prev*100:null,open:n(q.o),high:n(q.h),low:n(q.l),volume:n(q.v),tradeVolume:n(q.tv),upperLimit:n(q.u),lowerLimit:n(q.w),bidPrices:list(q.b),bidVolumes:list(q.g),askPrices:list(q.a),askVolumes:list(q.f),source:'TWSE MIS 公開市況'};}
async function official(code){for(const [url,market] of [['https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL','TWSE'],['https://www.tpex.org.tw/openapi/v1/tpex_mainboard_quotes','TPEx']]){try{const a=await fetchJson(url,5000);if(!Array.isArray(a))continue;const q=a.find(x=>String(x.Code||x.SecuritiesCompanyCode||'').trim()===code);if(!q)continue;const price=n(q.ClosingPrice??q.Close),change=n(q.Change);return{available:true,code,name:q.Name||q.CompanyName||code,market,date:String(q.Date||''),time:'最近交易資料',price,prevClose:Number.isFinite(price)&&Number.isFinite(change)?price-change:null,change,changePct:Number.isFinite(price)&&Number.isFinite(change)&&price-change?change/(price-change)*100:null,open:n(q.OpeningPrice??q.Open),high:n(q.HighestPrice??q.High),low:n(q.LowestPrice??q.Low),volume:n(q.TradeVolume??q.TradingShares),source:`${market} 官方 OpenAPI 最近交易資料`};}catch{}}return null;}
async function yahoo(code){for(const suffix of ['TW','TWO']){try{const j=await fetchJson(`https://query1.finance.yahoo.com/v8/finance/chart/${code}.${suffix}?interval=1d&range=5d`,5000),r=j?.chart?.result?.[0];if(!r)continue;const m=r.meta||{},qs=r.indicators?.quote?.[0]||{},cl=(qs.close||[]).filter(Number.isFinite),price=n(m.regularMarketPrice)??cl.at(-1),prev=n(m.chartPreviousClose??m.previousClose)??cl.at(-2),change=Number.isFinite(price)&&Number.isFinite(prev)?price-prev:null;if(!Number.isFinite(price))continue;const last=(qs.close||[]).length-1;return{available:true,code,name:m.longName||m.shortName||code,market:suffix==='TW'?'TWSE':'TPEx',date:'最近交易日',time:'延遲備援',price,prevClose:prev,change,changePct:change!=null&&prev?change/prev*100:null,open:n(m.regularMarketOpen)??n(qs.open?.[last]),high:n(m.regularMarketDayHigh)??n(qs.high?.[last]),low:n(m.regularMarketDayLow)??n(qs.low?.[last]),volume:n(m.regularMarketVolume)??n(qs.volume?.[last]),source:'Yahoo Finance 延遲行情（官方來源無法連線時備援）'};}catch{}}return null;}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=3, stale-while-revalidate=20');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Content-Type','application/json; charset=utf-8');const code=String(req.query?.code||'').trim().toUpperCase();if(!/^\d{4,6}[A-Z]?$/.test(code))return res.status(400).json({error:'股票代號格式錯誤'});let errors=[];for(const fn of [mis,official,yahoo]){try{const out=await fn(code);if(out){lastGoodQuote.set(code,{time:Date.now(),data:out});return res.status(200).json(out)}}catch(e){errors.push(e?.message||'failed')}}const stale=lastGoodQuote.get(code);if(stale?.data)return res.status(200).json({...stale.data,available:true,isRealtime:false,source:'最近成功行情（來源暫時中斷）',stale:true});return res.status(200).json({available:false,code,error:'所有行情來源暫時無法連線',errors});};
