const TWSE='https://openapi.twse.com.tw/v1',TPEX='https://www.tpex.org.tw/openapi/v1',UA='Mozilla/5.0 (compatible; ClariNavi/Current)';
const cache={t:0,v:null};
const txt=v=>String(v??'').trim(),num=v=>{const n=Number(String(v??'').replace(/,/g,'').replace(/%/g,'').replace(/^[＋+]/,'').trim());return Number.isFinite(n)?n:null};
function pick(o,ks){for(const k of ks)if(o&&o[k]!=null&&txt(o[k]))return o[k];return null}
async function fetchJson(url,timeout=5000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':UA,'Accept':'application/json,text/plain,*/*'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function roc(v){const s=txt(v).replace(/[\/-]/g,'');if(/^\d{7}$/.test(s))return`${+s.slice(0,3)+1911}-${s.slice(3,5)}-${s.slice(5,7)}`;if(/^\d{8}$/.test(s))return`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`;return txt(v)}
function anchors(n=2){const d=new Date(),o=[];for(let i=0;i<n;i++){const x=new Date(d.getFullYear(),d.getMonth()-i,1),y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0');o.push({ymd:`${y}${m}01`,slash:`${y}/${m}/01`})}return o}
function sma(a,n){if(a.length<n)return null;return a.slice(-n).reduce((s,x)=>s+x,0)/n}
function rsi(a,n=14){if(a.length<=n)return null;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i]-a[i-1];d>=0?g+=d:l-=d}const ag=g/n,al=l/n;return al===0?100:100-100/(1+ag/al)}
async function hist(c){const out=[];for(const a of anchors(2)){try{let j;if(c.market==='TWSE'){j=await fetchJson(`https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=${a.ymd}&stockNo=${c.code}&response=json`,3500);if(j?.stat==='OK')for(const r of j.data||[])out.push({date:roc(r[0]),close:num(r[6]),high:num(r[4]),volume:num(r[1])})}else{j=await fetchJson(`https://www.tpex.org.tw/www/zh-tw/afterTrading/tradingStock?date=${encodeURIComponent(a.slash)}&code=${c.code}&response=json`,3500);for(const r of j?.tables?.[0]?.data||[])out.push({date:roc(r[0]),close:num(r[6]),high:num(r[4]),volume:(num(r[1])||0)*1000})}}catch{}}
 const m=new Map();for(const x of out)if(x.date&&Number.isFinite(x.close))m.set(x.date,x);return[...m.values()].sort((a,b)=>a.date.localeCompare(b.date))}
async function newsHeat(cands){const list=cands.filter(x=>x.name&&x.name.length>1).slice(0,10);if(!list.length)return new Map();const q='('+list.map(x=>`"${x.name.replace(/"/g,'')}"`).join(' OR ')+')';try{const j=await fetchJson(`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(q)}&mode=artlist&maxrecords=50&format=json&sort=datedesc&timespan=1month`,7000),arts=Array.isArray(j?.articles)?j.articles:[],out=new Map(),cut=Date.now()-8*86400000;for(const a of arts){const title=txt(a.title),sd=String(a.seendate||''),d=/^\d{14}$/.test(sd)?new Date(`${sd.slice(0,4)}-${sd.slice(4,6)}-${sd.slice(6,8)}T${sd.slice(8,10)}:${sd.slice(10,12)}:00Z`):null;if(d&&d.getTime()<cut)continue;for(const c of list)if(title.includes(c.name)){const z=out.get(c.code)||{count:0,title:null,date:null};z.count++;if(!z.title){z.title=title;z.date=sd}out.set(c.code,z)}}return out}catch{return new Map()}}
function score(c,h,holder,news){const closes=h.map(x=>x.close),vols=h.map(x=>x.volume||0),ma20=sma(closes,20),r=rsi(closes),v5=sma(vols,5),v20=sma(vols,20),vr=v5&&v20?v5/v20:null,prev20=h.slice(-21,-1),breakout=prev20.length>=10&&c.close>=Math.max(...prev20.map(x=>x.high));let s=38,why=[];if(c.changePct>1){s+=Math.min(12,c.changePct*2);why.push(`當日上漲 ${c.changePct.toFixed(1)}%`)}if(ma20&&c.close>ma20){s+=12;why.push('站上 MA20')}if(r>=50&&r<=72){s+=10;why.push(`RSI ${r.toFixed(0)} 偏多`)}else if(r>78){s-=7;why.push('RSI 偏熱')}if(vr>1.25){s+=10;why.push(`量比 ${vr.toFixed(1)}×`)}if(breakout){s+=10;why.push('突破近20日高點')}if(holder?.continuous){s+=16;why.push(`400張大戶連續增加 +${holder.deltaBig400.toFixed(2)}pp`)}else if((holder?.weeklyDelta||0)>0.15){s+=9;why.push(`大戶本週增加 +${holder.weeklyDelta.toFixed(2)}pp`)}else if(holder?.big400>55){s+=3;why.push(`400張以上持股 ${holder.big400.toFixed(1)}%`)}if(c.event){s+=7;why.push('近期有官方重大訊息')}if((news?.count||0)>=3){s+=6;why.push(`近7日新聞熱度 ${news.count} 則`)}else if(news?.count){s+=3;why.push(`近7日有 ${news.count} 則相關新聞`)}return{score:Math.max(0,Math.min(100,Math.round(s))),ma20,rsi:r,volumeRatio:vr,breakout,reasons:why.slice(0,6),holderTrend:holder||null,newsHeat:news||null}}
async function current(){const out=[];try{const a=await fetchJson(`${TWSE}/exchangeReport/STOCK_DAY_ALL`);for(const x of Array.isArray(a)?a:[]){const code=txt(x.Code);if(!/^\d{4}$/.test(code)||code.startsWith('00'))continue;const close=num(x.ClosingPrice),chg=num(x.Change),vol=num(x.TradeVolume);if(!(close>10&&vol>500000&&Number.isFinite(chg)))continue;const prev=close-chg,pct=prev?chg/prev*100:0;out.push({code,name:txt(x.Name),market:'TWSE',close,change:chg,changePct:pct,volume:vol})}}catch{}
 try{const a=await fetchJson(`${TPEX}/tpex_mainboard_quotes`);for(const x of Array.isArray(a)?a:[]){const code=txt(pick(x,['SecuritiesCompanyCode','Code']));if(!/^\d{4}$/.test(code)||code.startsWith('00'))continue;const close=num(pick(x,['Close','ClosingPrice'])),chg=num(pick(x,['Change'])),vol=num(pick(x,['TradingShares','TradeVolume']));if(!(close>10&&vol>300000&&Number.isFinite(chg)))continue;const prev=close-chg,pct=prev?chg/prev*100:0;out.push({code,name:txt(pick(x,['CompanyName','Name'])),market:'TPEx',close,change:chg,changePct:pct,volume:vol})}}catch{}
 return out}
async function events(){const m=new Map();for(const [url,market] of [[`${TWSE}/opendata/t187ap04_L`,'TWSE'],[`${TPEX}/mopsfin_t187ap04_O`,'TPEx']]){try{const a=await fetchJson(url,4500);for(const x of Array.isArray(a)?a:[]){const code=txt(pick(x,['公司代號','CompanyCode','SecuritiesCompanyCode','Code']));if(!/^\d{4}$/.test(code))continue;const title=txt(pick(x,['主旨','Subject','重大訊息主旨']));if(title)m.set(`${market}:${code}`,title)}}catch{}}return m}
async function run(){const [cur,ev]=await Promise.all([current(),events()]);for(const c of cur)c.event=ev.get(`${c.market}:${c.code}`)||null;const pre=cur.filter(x=>x.changePct>0).sort((a,b)=>(b.changePct*2+Math.log10(b.volume||1))-(a.changePct*2+Math.log10(a.volume||1))).slice(0,14);const [news]=await Promise.all([newsHeat(pre)]);const enriched=[];let i=0;async function w(){while(i<pre.length){const c=pre[i++],h=await hist(c),t=score(c,h,null,news.get(c.code));enriched.push({...c,...t,event:c.event})}}await Promise.all(Array.from({length:Math.min(7,pre.length)},w));return enriched.sort((a,b)=>b.score-a.score||b.changePct-a.changePct).slice(0,14)}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=900');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Content-Type','application/json; charset=utf-8');try{if(cache.v&&Date.now()-cache.t<300000)return res.status(200).json({items:cache.v,cached:true});const v=await run();cache.t=Date.now();cache.v=v;return res.status(200).json({items:v,generatedAt:new Date().toISOString(),note:'強勢雷達綜合交易所公開行情技術面、MOPS 官方重大訊息與近期公開新聞熱度。為避免誤導，本版不使用第三方保存的 TDCC 歷史快照作為評分因子；不是個人化買進推薦。'})}catch(e){return res.status(200).json({items:[],error:e.message})}}
