const UA='Mozilla/5.0 (compatible; ClariNavi/Current; +https://vercel.app)';
function clean(s){return String(s||'').replace(/\s+/g,' ').trim()}
async function fetchJson(url,timeout=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':UA,'Accept':'application/json,text/plain,*/*'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function dateFmt(s){const x=String(s||'');if(/^\d{14}$/.test(x))return `${x.slice(0,4)}-${x.slice(4,6)}-${x.slice(6,8)}`;return x}
function median(a){const x=a.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
const brokerWords=['高盛','摩根士丹利','大摩','摩根大通','小摩','花旗','瑞銀','野村','里昂','匯豐','美銀','元大','富邦','國泰','凱基','中信','群益','統一','永豐','第一金','兆豐','玉山','康和','元富','外資','投顧','券商','證券'];
function brokerOf(title){return brokerWords.find(x=>title.includes(x))||''}
function twTarget(title){const pats=[/目標價(?:上看|升至|調高至|調升至|喊到|看至|達|為|下修至|降至)?\s*(?:新台幣|NT\$|NTD|\$)?\s*([0-9][0-9,]*(?:\.\d+)?)/i,/目標價[^0-9]{0,12}([0-9][0-9,]*(?:\.\d+)?)/i];for(const p of pats){const m=title.match(p);if(m){const v=Number(m[1].replace(/,/g,''));if(Number.isFinite(v)&&v>0)return v}}return null}
function usTarget(title){const pats=[/price target[^$0-9]{0,30}\$\s*([0-9][0-9,]*(?:\.\d+)?)/i,/target(?: price)?[^$0-9]{0,20}\$\s*([0-9][0-9,]*(?:\.\d+)?)/i];for(const p of pats){const m=title.match(p);if(m){const v=Number(m[1].replace(/,/g,''));if(Number.isFinite(v)&&v>0)return v}}return null}
module.exports=async function handler(req,res){
 res.setHeader('Cache-Control','s-maxage=900, stale-while-revalidate=3600');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Content-Type','application/json; charset=utf-8');
 const symbol=clean(req.query?.symbol).toUpperCase(),name=clean(req.query?.name),market=clean(req.query?.market||'TW').toUpperCase();if(!symbol&&!name)return res.status(400).json({error:'缺少股票'});
 const term=market==='US'?`(\"${symbol}\" OR \"${name||symbol}\") (\"price target\" OR analyst)`:`\"${name||symbol}\" (目標價 OR 外資 OR 投顧 OR 券商)`;
 const url=`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(term)}&mode=artlist&maxrecords=80&format=json&sort=datedesc&timespan=3months`;
 try{const j=await fetchJson(url),raw=Array.isArray(j?.articles)?j.articles:[],items=[],seen=new Set();for(const a of raw){const title=clean(a.title),u=clean(a.url);if(!title||!u||seen.has(u))continue;const target=market==='US'?usTarget(title):twTarget(title);if(!Number.isFinite(target))continue;const broker=market==='US'?clean(a.domain):brokerOf(title);if(market!=='US'&&!broker)continue;seen.add(u);items.push({target,title,url:u,source:clean(a.domain),broker:broker||clean(a.domain),date:dateFmt(a.seendate)});if(items.length>=12)break}const vals=items.map(x=>x.target);return res.status(200).json({symbol,name,market,count:items.length,median:median(vals),low:vals.length?Math.min(...vals):null,high:vals.length?Math.max(...vals):null,items,source:'近期公開新聞標題中的券商／分析師目標價摘錄（GDELT 索引）',note:'不是完整券商共識資料庫；僅納入近期公開新聞標題可辨識的目標價，需以原始研究報告與發布日期交叉確認。'})}catch(e){return res.status(200).json({symbol,name,market,count:0,items:[],error:e.message})}
}
